today-is-first/oneul

frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/feed/FeedCreateBtn.tsx, frontend/src/components/feed/FeedCreateModal.tsx, frontend/src/components/home/Home.tsx
=> [Feat] 피드 작성 DB 연동

backend/demo/pom.xml, backend/demo/src/main/java/store/oneul/mvc/config/SwaggerConfig.java
Resolves: #109
어떤 변경 사항이 있나요?
pom.xml수정
SwaggerConfig 생성
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> [Feat] Swagger 설정 

frontend/src/api/api.ts, frontend/src/api/challenge.ts, frontend/src/components/challenge/ChallengeList.tsx, frontend/src/components/challengeDetail/ChallengeDetailPage.tsx, frontend/src/components/challengeDetail/ChellengeDetail.tsx, frontend/src/hooks/useApiHooks.ts, frontend/src/hooks/useChallenge.ts, frontend/src/types/Challenge.ts
Resolves: #27 
어떤 변경 사항이 있나요?
- api 메서드 파일 및 폴더명 수정 (useApi -> api)
- useQuery, useMutation을 활용한 useApiHooks 생성 
- 챌린지 디테일 페이지 api 연결 
- 챌린지 타입 파일 별도 생성
=> [Feat] 챌린지 디테일 api 연결 

frontend/src/components/home/CommunityFeed.tsx, frontend/src/components/home/Home.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx
Resolves: #115 
어떤 변경 사항이 있나요?
=> [Feat] 다른 사용자 피드 컴포넌트 퍼블리싱

frontend/src/App.tsx, frontend/src/components/challengeSearch/ChallengeSearchPage.tsx, frontend/src/components/common/Badge.tsx, frontend/src/components/common/NavBar.tsx, frontend/src/components/home/CommunityFeed.tsx, frontend/src/components/home/Home.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx
Resolves: #130 
어떤 변경 사항이 있나요?
=> [Feat] 챌린지 룸 조회 페이지 구현

frontend/public/svgs/default-profile.svg, frontend/src/components/common/LoginBtn.tsx, frontend/src/components/feed/FeedCreateModal.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx, frontend/src/components/sideBar/SideBar.tsx, frontend/src/components/sideBar/SidePanelToggleBtn.tsx, frontend/src/layouts/MainLayout.tsx
Resolves: #117 
어떤 변경 사항이 있나요?
=> [Feat] 사이드바에 로그인 버튼 추가

frontend/public/svgs/default-profile.svg, frontend/src/App.tsx, frontend/src/components/chat/ChatBanner.tsx, frontend/src/components/chat/ChatHeader.tsx, frontend/src/components/chat/ChatMessageList.tsx, frontend/src/components/chat/ChatRoom.tsx, frontend/src/components/common/LoginBtn.tsx, frontend/src/components/feed/FeedCreateModal.tsx, frontend/src/components/home/Home.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx, frontend/src/components/sideBar/SideBar.tsx, frontend/src/components/sideBar/SidePanelToggleBtn.tsx, frontend/src/index.css, frontend/src/layouts/MainLayout.tsx
=> [Feat] 채팅창 챌린지 상세보기 기능 구현

backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java, backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java, backend/demo/src/main/java/store/oneul/mvc/feed/dto/ContentDTO.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java, backend/demo/src/main/resources/mappers/FeedMapper.xml, frontend/src/components/feed/FeedCreateModal.tsx, frontend/src/components/feed/FeedUpdateModal.tsx, frontend/src/components/feed/MyFeedCard.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx
Resolves: #162 
어떤 변경 사항이 있나요?
=> [Feat] 오늘의 인증 챌린지 선택 기능 추가 및 리액트 쿼리 캐싱 개선

backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java, backend/demo/src/main/java/store/oneul/mvc/payment/client/TossClient.java, backend/demo/src/main/java/store/oneul/mvc/payment/config/RestClientConfig.java, backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java, backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java, backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentConfirmRequest.java, backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossConfirmRequest.java, backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossConfirmResponse.java, backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossErrorInfo.java, backend/demo/src/main/java/store/oneul/mvc/payment/exception/PaymentConfirmException.java, backend/demo/src/main/java/store/oneul/mvc/payment/service/TossConfirmService.java, backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java, backend/demo/src/main/java/store/oneul/mvc/payment/validator/PaymentValidator.java, backend/demo/src/main/resources/mappers/PaymentMapper.xml
- 클라이언트 요청과 Toss API 요청을 분리하기 위한 DTO 분리 (PaymentConfirmRequest, TossConfirmRequest)
- Toss API 응답 및 실패 응답 매핑용 DTO (TossConfirmResponse, TossErrorInfo) 작성
- Redis, 주문정보 검증 및 중복 결제 방지를 위한 PaymentValidator 구현
- Toss 결제 승인 API 호출을 위한 TossClient 구현 (Basic 인증, 에러 처리 포함)
- 결제 승인 비즈니스 로직을 조립하는 PaymentUsecase 구현
- 예외 발생 시 일관된 API 응답을 위한 PaymentConfirmException 및 글로벌 예외처리기 구현
- Spring Bean으로 RestClient 등록 및 base URL 설정
Resolves: #153 
어떤 변경 사항이 있나요?
- 클라이언트가 결제 승인 요청 시 전달하는 전체 데이터 DTO
- 내부 결제 검증 및 로직 수행을 위해 `challengeId` 필드 추가 (Redis 검증 및 DB 연동용)
- Toss API 호출 시 필요한 최소 필드(`orderId`, `paymentKey`, `amount`)만 포함하는 전용 DTO
- 내부 DTO와 외부 API 요청 DTO 분리로 데이터 명확성 및 유지보수성 향상
- Toss 결제 승인 API 응답 매핑용 DTO
- 결제 승인 시각(`approvedAt`), 상태(`status`) 등 결제 결과 정보 포함
- Toss API 실패 시 반환되는 에러 JSON을 매핑하기 위한 DTO
- 에러 …
=> [Feat] Toss 결제 승인 기능 구현 및 예외 처리 추가

backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java, backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java, backend/demo/src/main/java/store/oneul/mvc/feed/dto/ChallengeFeedDTO.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java, backend/demo/src/main/resources/mappers/FeedMapper.xml, frontend/src/components/challengeDetail/ChallengeDetailPage.tsx, frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/feed/FeedDetailModal.tsx, frontend/src/components/home/CommunityFeedItem.tsx, frontend/src/components/home/CommunityFeedList.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx, frontend/src/hooks/useFeed.ts
Resolves: #165 
어떤 변경 사항이 있나요?
- 피드 디테일 모달 CSS 변경
- 챌린지 디테일 페이지에서 피드 클릭 시 유저 프로필 보이게 변경
- 홈페이지에서 피드 클릭 시 피드 디테일 모달 보이는 기능 구현
=> [Feat] 피드 디테일 모달 UI 변경 및 홈페이지 피드 클릭 시 디테일 모달 기능 구현

backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java, backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java, backend/demo/src/main/java/store/oneul/mvc/feed/dto/ChallengeFeedDTO.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java, backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java, backend/demo/src/main/resources/mappers/FeedMapper.xml, frontend/src/components/challengeDetail/ChallengeDetailPage.tsx, frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/feed/FeedDetailModal.tsx, frontend/src/components/home/CommunityFeedItem.tsx, frontend/src/components/home/CommunityFeedList.tsx, frontend/src/components/home/MonthlyStats.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx, frontend/src/components/home/StreakCalendar.tsx, frontend/src/hooks/useFeed.ts, frontend/src/layouts/MainLayout.tsx
Resolves: #164 
어떤 변경 사항이 있나요?
- UI 비율 변경
=> [Design] 월간 통계, 스트릭 비율 수정

frontend/src/App.tsx, frontend/src/api/payment.ts, frontend/src/components/challengeRegist/ChallengeDetailModal.tsx, frontend/src/components/payment/ChallengePaymentPage.tsx
Resolves: #172 
어떤 변경 사항이 있나요?
- 결제 페이지 퍼블리싱, 라우팅
- 토스 SDK 연결
- orderId 요청 api 함수 생성 및 페이지 적용
=> [Feat] 결제 페이지 퍼블리싱 & orderID 요청 api 함수 연결 

backend/demo/src/main/java/store/oneul/mvc/config/DbConfig.java, backend/demo/src/main/java/store/oneul/mvc/config/ErrorCode.java, backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java, backend/demo/src/main/java/store/oneul/mvc/config/RestClientConfig.java
Resolves: #153
어떤 변경 사항이 있나요?
- RestClientConfig를 store.oneul.mvc.config로 이동
- MyBatis alias 충돌 방지를 위해 설정 위치 조정
- PaymentDAO 주입 오류 해결 (해당 DAO에 @Mapper 추가 또는 @MapperScan 적용)
- GlobalExceptionHandler에 InvalidParameterException, NotFoundException 핸들러 추가
- ErrorCode enum에 NOT_FOUND 항목 추가
작업 내용 확인
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> [Feat] RestClient 설정 정리 및 글로벌 예외 처리 확장

frontend/src/components/challengeSearch/CategoryTab.tsx, frontend/src/components/challengeSearch/ChallenegeModeTab.tsx, frontend/src/components/challengeSearch/ChallengeSearchPage.tsx, frontend/src/components/challengeSearch/ChallengeSearchRoomItem.tsx, frontend/src/components/challengeSearch/ChallengeStatusTab.tsx, frontend/src/constants/challengeSearchContants.ts
Resolves: #166
어떤 변경 사항이 있나요?
- 챌린지 조회 페이지 컴포넌트 분리 리팩토링
- 챌린지 조회 페이지 챌린지 상태 필터 기능 구현
=> [Feat] 챌린지 조회 페이지 챌린지 상태 필터 기능 구현

backend/demo/src/main/java/store/oneul/mvc/chat/dao/ChatDAO.java, backend/demo/src/main/java/store/oneul/mvc/chat/dto/FetchPreviousMessagesRequest.java, backend/demo/src/main/java/store/oneul/mvc/chat/handler/ChatEventHandler.java, backend/demo/src/main/java/store/oneul/mvc/chat/service/ChatService.java, backend/demo/src/main/resources/mappers/ChatMapper.xml, frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/chat/ChatMessageList.tsx, frontend/src/components/chat/ChatRoom.tsx, frontend/src/stores/feedStore.tsx, frontend/src/stores/socketStore.tsx
Resolves: #169 
어떤 변경 사항이 있나요?
- [FE] 무한 스크롤 기능 구현
- [BE] 이전 채팅 불러오는 기능 구현
- [FE] 이전 채팅 추가되어도 현재 위치 고정 기능
https://github.com/user-attachments/assets/98237a3d-ac6c-4a33-9064-673c1752fe74
=> [Feat] 채팅 무한 스크롤 기능 구현

backend/demo/src/main/java/store/oneul/mvc/chat/dao/ChatDAO.java, backend/demo/src/main/java/store/oneul/mvc/chat/dto/FetchPreviousMessagesRequest.java, backend/demo/src/main/java/store/oneul/mvc/chat/handler/ChatEventHandler.java, backend/demo/src/main/java/store/oneul/mvc/chat/service/ChatService.java, backend/demo/src/main/resources/mappers/ChatMapper.xml, frontend/src/App.tsx, frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/challengeSearch/CategoryTab.tsx, frontend/src/components/challengeSearch/ChallenegeModeTab.tsx, frontend/src/components/challengeSearch/ChallengeSearchPage.tsx, frontend/src/components/challengeSearch/ChallengeSearchRoomItem.tsx, frontend/src/components/challengeSearch/ChallengeStatusTab.tsx, frontend/src/components/chat/ChatMessageList.tsx, frontend/src/components/chat/ChatRoom.tsx, frontend/src/components/common/LoginBtn.tsx, frontend/src/components/sideBar/SideBar.tsx, frontend/src/constants/challengeSearchContants.ts, frontend/src/stores/challengeStore.tsx, frontend/src/stores/feedStore.tsx, frontend/src/stores/socketStore.tsx, frontend/src/stores/userStore.tsx, frontend/src/utils/userUtils.ts
Resolves: #181
어떤 변경 사항이 있나요?
- 엑세스 토큰 만료 시 로그아웃 처리
- 로그아웃 시 전역 상태 초기화 및 리액트 쿼리 초기화
https://github.com/user-attachments/assets/e5e4b257-278b-48e0-b28c-1038922a2a41
=> [Feat] 로그아웃 시 전역상태 초기화 및 리액트 쿼리 캐시 초기화

backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
Resolves: #153
어떤 변경 사항이 있나요?
- toss에서 허용하지 않는 특수 문자 규정이 있어서 orderId 구분자 `_`로 변경
=> [Fix] orderID 포맷수정

backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
Resolves: #154
어떤 변경 사항이 있나요?
트랜잭션 서비스 주석 해제
=> [Chore] 트랜잭션 서비스 주석 해제

backend/demo/src/main/java/store/oneul/mvc/security/oauth/OAuth2SuccessHandler.java, backend/demo/src/main/java/store/oneul/mvc/security/oauth/service/OAuthService.java, backend/demo/src/main/java/store/oneul/mvc/security/oauth/service/OAuthServiceImpl.java, backend/demo/src/main/java/store/oneul/mvc/security/token/TokenHelper.java, backend/demo/src/main/java/store/oneul/mvc/user/controller/UserController.java, backend/demo/src/main/java/store/oneul/mvc/user/dto/LoginResultDTO.java, backend/demo/src/main/java/store/oneul/mvc/user/service/UserServiceImpl.java, frontend/src/components/login/GuestLoginBtn.tsx, frontend/src/components/login/LoginPage.tsx, frontend/src/components/login/OAuthBtn.tsx
Resolves: #189
어떤 변경 사항이 있나요?
- 하드코딩된 상수 application.properties로 분리
- [BE] 쿠키 및 토큰 생성 로직 리팩토링
- [FE] 게스트 로그인 버튼 퍼블리싱
=> [Feat] 게스트 로그인 기능 구현

backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java, backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java, backend/demo/src/main/java/store/oneul/mvc/challenge/exception/ChallengeAlreadyJoinedException.java, backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java, backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java, backend/demo/src/main/java/store/oneul/mvc/config/ErrorCode.java, backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java, backend/demo/src/main/resources/mappers/ChallengeMapper.xml, frontend/package-lock.json, frontend/package.json, frontend/src/api/challenge.ts, frontend/src/components/Toast/Toast.tsx, frontend/src/components/Toast/ToastBox.tsx, frontend/src/components/Toast/ToastList.tsx, frontend/src/components/challengeDetail/ChellengeDetail.tsx, frontend/src/components/challengeRegist/ChallengeDetailModal.tsx, frontend/src/components/challengeSearch/ChallengeSearchPage.tsx, frontend/src/components/challengeSearch/ChallengeSearchRoomItem.tsx, frontend/src/components/common/Badge.tsx, frontend/src/components/payment/PaymentFailPage.tsx, frontend/src/components/payment/PaymentSuccessPage.tsx, frontend/src/hooks/useApiHooks.ts, frontend/src/hooks/useChallenge.ts, frontend/src/index.css, frontend/src/types/ApiResponse.ts, frontend/src/types/Toast.ts
Resolves: #146
어떤 변경 사항이 있나요?
- 토스트 컴포넌트 추가
- 챌린지 디테일 모달 내부 디자인 수정
- 컬러 변수 추가, 수정, 토스트 애니메이션 추가 
- 유료/무료 공개/비공개 챌린지 룸 참가 FE 분기처리 
- 백엔드 챌린지 참가 로직 추가 
- 챌린지 참가 관련 글로벌 익셉션 추가 
- 챌린지 뱃지 타입 추가 및 디자인 추가 
- 챌린지 가입 요청 FE 훅, api 함수 추가
=> [Feat] 챌린지 가입 BE&FE 로직 구현 및 상황별 분기처리, 챌린지 디테일 모달 수정 

frontend/src/components/common/Dialog.tsx, frontend/src/components/feed/FeedDetailItem.tsx, frontend/src/components/feed/FeedDetailModal.tsx, frontend/src/components/home/MyWorkoutDashboard.tsx, frontend/src/components/home/WorkoutModal.tsx, frontend/src/index.css, frontend/src/utils/date.ts
Resolves: #127 
어떤 변경 사항이 있나요?
- 스트릭 클릭 시 피드 뜨는 기능 구현
=> [Feat] 스트릭 클릭 시 피드 뜨는 기능 구현

frontend/src/components/challengeRegist/ChallengeDetailModal.tsx, frontend/src/hooks/useChallenge.ts
Resolves: #194 
어떤 변경 사항이 있나요?
- 성공시 페이지로 바로 이동하도록 코드 추가했습니다.
=> [Feat] 챌린지 참여 성공시 챌린지 디테일 페이지 이동 구현, 챌린지 데이터 리페치 

frontend/src/components/challengeCreate/ChallengeRoomForm.tsx, frontend/src/components/challengeSearch/ChallegeCreateBtn.tsx, frontend/src/components/challengeSearch/ChallengeSearchPage.tsx, frontend/src/components/home/WorkoutModal.tsx
Resolves: #24
어떤 변경 사항이 있나요?
- 챌린지 생성 컴포넌트 퍼블리싱
=> [Feat] 챌린지 생성 컴포넌트 퍼블리싱

backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java, backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java, backend/demo/src/main/resources/mappers/ChallengeMapper.xml, frontend/src/App.tsx, frontend/src/components/challengeCreate/ChallengeCreatePage.tsx, frontend/src/components/challengeCreate/ChallengeRoomForm.tsx, frontend/src/components/challengeCreate/CustomDateInput.tsx, frontend/src/components/challengeCreate/PublicToggle.tsx, frontend/src/components/challengeCreate/SelectBlock.tsx, frontend/src/components/challengeCreate/TextAreaBlock.tsx, frontend/src/components/common/InputBlock.tsx
Resolves: #24 
어떤 변경 사항이 있나요?
- 챌린지 생성 기능
- 챌린지 생성 시 챌린지 참가 기능 구현
=> [Feat] 챌린지 생성 기능 구현

backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java, backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java, backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java, backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java, backend/demo/src/main/resources/mappers/ChallengeMapper.xml, frontend/src/App.tsx, frontend/src/components/challengeCreate/ChallengeCreatePage.tsx, frontend/src/components/challengeCreate/ChallengeRoomForm.tsx, frontend/src/components/challengeCreate/CustomDateInput.tsx, frontend/src/components/challengeCreate/PublicToggle.tsx, frontend/src/components/challengeCreate/SelectBlock.tsx, frontend/src/components/challengeCreate/TextAreaBlock.tsx, frontend/src/components/common/InputBlock.tsx, frontend/src/components/mypage/MyChallengeList.tsx, frontend/src/stores/challengeStore.tsx
Resolves: #205 
어떤 변경 사항이 있나요?
- 사용자의 모든 챌린지 목록 가져오는 기능 구현
=> [Feat] 사용자의 모든 챌린지 조회 기능

frontend/src/components/feed/FeedCreateBtn.tsx, frontend/src/components/mypage/MyPage.tsx, frontend/src/components/mypage/ReceiptList.tsx, frontend/src/stores/receiptStore.tsx, frontend/src/types/Receipt.ts, frontend/src/utils/dataUtils.ts
Resolves: #210
어떤 변경 사항이 있나요?
- 영수증 목록 퍼블리싱 및 기능 구현
- 마이 페이지 탭 기능 구현
=> [Design] 마이페이지 영수증 목록 퍼블리싱

frontend/src/components/challengeDetail/ChallengeDetailPage.tsx, frontend/src/components/challengeDetail/ChallengeFeed.tsx, frontend/src/components/common/CheckStatus.tsx, frontend/src/components/feedCheck/ChallengeFeedCheck.tsx
Resolves: #30
어떤 변경 사항이 있나요?
- 챌린지 피드체크 컴포넌트 생성
- 챌린지 디테일 디자인 수정
=> [Feat] 챌린지 피드 체크 컴포넌트 구현 
